apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
      - mountPath: /giropops
        name: first-emptydir
    resources: 
      limits:
        memory: "128Mi"
        cpu: "1"
      requests:
        memory: "64Mi"
        cpu: "0.5"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: first-emptydir
    emptyDir:
      sizeLimit: 256Mi
