apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
    service: webserver
  name: girus
spec:
  containers:
  - image: ubuntu
    name: ubuntu 
    args: 
    - sleep
    - "1800"
    resources: 
      limits:
        memory: "128Mi"
        cpu: "0.5"
      requests:
        memory: "63Mi"
        cpu: "0.3"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
